  - name: 4. Commit dan Push hasil
    run: |
      git config --global user.name 'github-actions'
      git config --global user.email 'github-actions@github.com'
      git add kilatlive_playlist.m3u || echo "Tidak ada playlist baru untuk di-commit"
      git diff --staged --quiet || git commit -m "Update playlist live event"
      git push
